djangodreams/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('about/', views.About.as_view(), name="about"),
    path('activities', views.ActList.as_view(), name="act_list"),
    path('activities/new/', views.ActCreate.as_view(), name="act_create"),
    path('activities/<int:pk>/', views.ActDetail.as_view(), name="act_detail"),
    path('activities/<int:pk>/update', views.ActUpdate.as_view(), name="act_update"),
    path('activities/<int:pk>/delete', views.ActDelete.as_view(), name="act_delete"),
    path('user/<username>/', views.profile, name="profile"),
    path('reviews/', views.reviews_index, name="reviews_index"),
    path('reviews/<int:review_id>', views.reviews_show, name="reviews_show"),
    path('reviews/create/', views.ReviewCreate.as_view(), name="reviews_create"),
    path('reviews/<int:pk>/update/', views.ReviewUpdate.as_view(), name="reviews_update"),
    path('reviews/<int:pk>/delete/', views.ReviewDelete.as_view(), name="reviews_delete"),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register')
]

main_app/models.py
from secrets import choice
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

LABEL_CHOICES = (
    ("Food", "food"),
    ("Activity", "activity"),
)

ACTIVE_CHOICES = (
    ("CP", "Couch Potato"),
    ("NAS", "Not As Active"),
    ("A", "Active"),
    ("SOA", "Sort of Active"),
    ("T", "Triathlon"),
)

class Review(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    weather = models.CharField(max_length=100)
    active = models.CharField(max_length=40, choices= ACTIVE_CHOICES)

    def __str__(self):
        return self.name

class Act(models.Model):
    name = models.CharField(max_length=50)
    label = models.CharField(max_length=20, choices = LABEL_CHOICES)
    rating = models.IntegerField()
    price = models.IntegerField()
    location = models.CharField(max_length=100)
    images = models.CharField(max_length=250)
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    review = models.ManyToManyField(Review)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

main_app/forms.py
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=3, max_length=120)
    email = forms.EmailField(label='Enter Email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 =  forms.CharField(label= 'Confirm password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        u = User.objects.filter(username=username)
        if u.count():
            raise ValidationError("Username has been used")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        u = User.objects.filter(email=email)
        if u.count():
            raise ValidationError("Email has been used")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password does not match")

        return password2

    def save_login(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

main_app/views.py
from django.forms import ValidationError
from django.urls import reverse
from dataclasses import fields
from pipes import Template
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.views.generic.base import TemplateView
from .models import Act, Review
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
# auth imports
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import CustomUserCreationForm



class Home(View):    
    def get(self, request):
        return HttpResponse("Wholesome Home")

class About(View):
    def get(self, request):
        return HttpResponse("About Wholesome")

class Home(TemplateView):
    template_name = "home.html"

class About(TemplateView):
    template_name = "about.html"


class ActList(TemplateView):
    template_name = 'actlist.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name")
        if name != None:
            context["acts"] = Act.objects.filter(name__icontains=name)
            context["header"] = f"Searching for {name}"
        else:
            context["acts"] = Act.objects.all()
            context["header"] = "Activities"
        return context

@method_decorator(login_required, name='dispatch')
class ActCreate(CreateView):
    model = Act
    fields = '__all__'
    # fields = ['name', 'label', 'rating', 'price', 'location', 'images', 'review']
    template_name = 'act_create.html'
    def get_success_url(self):
        return reverse('act_detail', kwargs={'pk': self.object.pk})
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect('/activities')

class ActDetail(DetailView):
    model = Act
    template_name = "act_detail.html"

@method_decorator(login_required, name='dispatch')
class ActUpdate(UpdateView):
    model = Act
    # fields = ['name', 'label', 'rating', 'price', 'location', 'images', 'review']
    fields = '__all__'
    template_name = "act_update.html"
    def get_success_url(self):
        return reverse('act_detail', kwargs={'pk': self.object.pk})

@method_decorator(login_required, name='dispatch')
class ActDelete(DeleteView):
    model = Act
    template_name = "act_delete_confirm.html"
    success_url = "/activities"

@login_required
def profile(request, username):
    user = User.objects.get(username=username)
    acts = Act.objects.filter(user=user)
    return render(request, 'profile.html', {'username': username, 'acts': acts})

# Reviews Crud
def reviews_index(request):
    reviews = Review.objects.all()
    return render(request, 'reviews_index.html', {'reviews': reviews})

def reviews_show(request, review_id):
    review = Review.objects.get(id=review_id)
    return render(request, 'reviews_show.html', {'review': review})

@method_decorator(login_required, name='dispatch')
class ReviewCreate(CreateView):
    model = Review
    fields = '__all__'
    template_name ='review_form.html'
    success_url = '/reviews'

@method_decorator(login_required, name='dispatch')
class ReviewUpdate(UpdateView):
    model = Review
    fields = ['name', 'description', 'weather', 'active']
    template_name = 'reviews_update.html'
    success_url = '/reviews'

@method_decorator(login_required, name='dispatch')
class ReviewDelete(DeleteView):
    model = Review
    template_name = 'review_confirm_delete.html'
    success_url = '/reviews'

# django auth
# def signup_view(request):
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#             print('Hello', user.username)
#             messages.success(request, 'Account Created Successfully')
#             return HttpResponseRedirect('/user/'+str(user))
#         else:
#             return render(request, 'signup.html', {'form': form})
#     else:
#         form = UserCreationForm()
#         return render(request, 'signup.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save_login()
            login(request, user)
            messages.success(request, 'Account Created')
            return HttpResponseRedirect('/user/'+str(user))
    else:
        form = CustomUserCreationForm()
    return render(request, 'register.html', {'form': form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/activities')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            usr = form.cleaned_data['username']
            pas = form.cleaned_data['password']
            user = authenticate(username = usr, password = pas)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/user/'+usr)
                else:
                    return render(request, 'login.html', {'form': form})
            else:
                return render(request, 'login.html', {'form': form})
        else:
            return render(request,'register.html', {'form': form}) 
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})
    

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <h1>About</h1>
{% endblock %}

<!-- testing github transfer -->

main_app/templates/act_create.html
{% extends 'base.html' %}
{% block content %}
    <div class="card-color">
        <div id="color-cord" class="card">
            <span class="text">Create Activity</span>
            <p>
                <form method="post">
                    <!-- security token -->
                    {% csrf_token %}
                    <table>{{form.as_table}}</table>
                    <input class="inp" type="submit" value="Submit" />
                </form>
            </p>
        </div>
      </div>
{% endblock %}

main_app/templates/act_delete_confirm.html
{% extends 'base.html' %}
{% block content %}
<h1>Are you sure you want to DELETE {{act.name}}?</h1>
<form method="post">
    {% csrf_token %}
    <div>
        <!-- confirm act delete -->
        <input type="submit" value="Confirm" />
        <!-- redirects back to cancel -->
        <a href="{% url 'act_detail' act.pk %}" >Cancel</a>
    </div>
</form>

{% endblock %}

main_app/templates/act_detail.html
{% extends 'base.html' %}
{% block content %}
<nav>
    <a href="{% url 'act_list' %}"> Home</a>
</nav>
    <div>
        <img src="{{act.images}}" alt="{{act.name}}" />
    </div>
    <h1>{{act.name}}</h1>
    <div>
        <h3>Food or Activity: {{act.label}}</h3>
        <h3>Price: {{act.price}}</h3>
        <h3>Rating: {{act.rating}}</h3>
        <h3>location: {{act.location}}</h3>
    </div>
    {% for review in act.reviews.all %}
        <div>{{review.name}}
            {{ review.description }}
        </div>
    {% empty %}
        <div> Activity has no reviews </div>
    {% endfor %}
    <div>
        <a href="{% url 'act_update' act.pk %}">Update</a>
        <a href="{% url 'act_delete' act.pk %}">Delete</a>
    </div>

{% endblock %}

main_app/templates/act_update.html
{% extends 'base.html' %}
{% block content %}
<h1>Update {{act.name}}</h1>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="login">
    <h1>Welcome Home</h1>
    <div>
        <a href="{% url 'login' %}"><img src="https://images.pexels.com/photos/6532589/pexels-photo-6532589.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" width="500" height="800"></a>
    </div>
</div>
{% endblock %}

main_app/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="card-color ">
    <h1>Login</h1>
    <form method="post" action=".">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit" />
    </form>
</div>


{% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>{{ username }}'s Recommendations</h1>
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% for act in acts %}
    <a href="/activities/{{ act.id }}">
        <h3>{{ act.name }}</h3>
    </a>
    {% endfor %}
{% endblock %}

main_app/templates/review_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Review</h1>
    <h4>Are you sure you want to DELETE {{ review }}?</h4>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!">
        <a href={% url 'reviews_show' review.id %}>Cancel</a>
    </form>
{% endblock %}

main_app/templates/review_form.html
{% extends 'base.html' %}

{% block content %}
<div>
    <div class="card-color">
        <div class="card">
            <span class="text">Create Review</span>
            <p>
                <form method="post">
                    <!-- security token -->
                    {% csrf_token %}
                    <table>{{form.as_table}}</table>
                    <input class="inp" type="submit" value="Submit" />
                </form>
            </p>
        </div>
      </div>
</div>
{% endblock %}

main_app/templates/reviews_index.html
{% extends 'base.html' %}
{% block content %}

<h1 id="review-title">Review List</h1>

{% for review in reviews %}
    <div class="list">
        <a class="hover decor" href="{% url 'reviews_show' review.id %}">
            <div class="card-content">
                <span>{{ review.name}}</span>
                <p>Activity Level {{ review.active }}</p>
                <p>Weather: {{ review.weather }}</p>
                <p>Description: {{review.description }}</p>
            </div>
        </a>
    </div>
{% endfor %}

{% endblock %}

main_app/templates/reviews_show.html
{% extends 'base.html' %}
{% block content %}

<h1>Reviews</h1>

<div>
    <div class="review-container">
        <span>{{ review.name }}</span>
        <p>Activity Level {{ review.active }}</p>
        <p>Weather: {{ review.weather }}</p>
        <p>Description: {{ review.description }}</p>
        <p>Review For:</p>
        {% for act in review.act_set.all %}
            <p>{{act.name}}</p>
        {% empty %}
            <p>Nobody has this review</p>
        {% endfor %}
    </div>
    <div>
        <a href="{% url 'reviews_update' review.id %}">Edit</a>
        <a href="{% url 'reviews_delete' review.id %}">Delete</a>
    </div>
</div>
{% endblock %}

main_app/templates/reviews_update.html
{% extends 'base.html' %}

{% block content %}
    <h1> Reviews Update</h1>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Update"/>
    </form>
{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>Sign up</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>

{% endblock %}